name: Build LaTeX PDF

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  build-latex:
    uses: ./.github/workflows/build.yml
    with:
      working-directory: 'paper'
      tex-file: 'vision.tex'